version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:4306 -timeout 20s bundle exec unicorn -p 3000 -c /furima-30526/config/unicorn.conf.rb 
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db 
    ports:
      - "3000:3000"
    volumes:
      - .:/furima-30526:cached 
      #ソケット通信用ファイルをnginxコンテナと共有
      - tmp-data:/furima-30526/tmp/sockets
      #画像データとかをnginxと共有
      - public-data:/furima-30526/public
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_KEY: ${AWS_SECRET_KEY}
        PAYJP_SECRET_KEY: ${PAYJP_SECRET_KEY}
        PAYJP_PUBLIC_KEY: ${PAYJP_PUBLIC_KEY}
        RAILS_ENV: development
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '4306:3306'
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    #dbのデータを永続化しておく
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/furima-30526/tmp/sockets
      - public-data:/furima-30526/public
    depends_on:
      - web 

volumes:
  public-data:
  tmp-data:
  mysql-data: